apiVersion: v1
kind: Pod
metadata:
  name: pv-test
spec:
  volumes:
    - name: pv-test
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: pv-test
      image: httpd:2.4.46
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs"
          name: pv-test